server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/cartdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

catalog:
  service:
    url: http://localhost:8081/api/catalog

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        minimumNumberOfCalls: 3
        failureRateThreshold: 40
        waitDurationInOpenState: 5s
        slidingWindowSize: 10
        slidingWindowType: TIME_BASED
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

    instances:
      catalogService:
        baseConfig: default
        minimumNumberOfCalls: 12
        permittedNumberOfCallsInHalfOpenState: 12

  retry:
    instances:
      catalogService:
        maxAttempts: 3
        waitDuration: 1
        retryExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException